### ISSUE TITLE
Error: Missing error handler on `socket`.

### ISSUE THREAD

**Issue by vnen** [thedeeno/web-component-tester-istanbul#5]
When I try to use this plugin (I'm using last npm version: 0.8.0 and wct 2.2.6), I get the following error:

```
Missing error handler on `socket`.
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Object.Collector.add (/home/george/Workspace/mediator-writerstrail/node_modules/web-component-tester-istanbul/node_modules/istanbul/lib/collector.js:68:16)
    at /home/george/Workspace/mediator-writerstrail/node_modules/web-component-tester-istanbul/lib/plugin.js:19:20
    at emitThree (events.js:97:13)
    at Context.emit (events.js:172:7)
    at BrowserRunner.onEvent (/home/george/Workspace/mediator-writerstrail/node_modules/web-component-tester/runner/browserrunner.js:135:18)
    at Socket.<anonymous> (/home/george/Workspace/mediator-writerstrail/node_modules/web-component-tester/runner/steps.js:81:31)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Socket.onevent (/home/george/Workspace/mediator-writerstrail/node_modules/web-component-tester/node_modules/socket.io/lib/socket.js:330:8)
```
The error point me to the middle line in this portion of your code (`lib/plugin.js`):

```node
emitter.on('sub-suite-end', function(browser, data) {
  this.collector.add(data.__coverage__);
}.bind(this));
```

And, with a `console.log` I notice that the `data` is an empty object, so this may be an issue with WCT itself.

**Comment by jamstooks** [comment]
I'm in the same boat. @vnen, did you ever figure out a work-around?

**Comment by vnen** [comment]
@jamstooks not really. I snuff around but couldn't figure out from where this `data` should come from.

**Comment by thedeeno** [comment]
WCT has been going through a bit of churn lately. I suspect the contract I originally created has changed a little bit. I'm not currently using this plugin but I should be returning to the project that uses this in the next few weeks. I'll bring this library up-to-date then.

In the mean time you might be able to use an older version of WCT to generate reports.

**Comment by priyabrat1801** [comment]
Has this been fixed?? I am facing the same.

**Comment by weissnoam** [comment]
facing the same problem. any news?

**Comment by priyabrat1801** [comment]
@thedeeno Could you please suggest which version of WCT to be used to get this plugin working? I am using 3.2.0 for WCT & 0.8.0 for the istanbul plugin.

**Comment by apowers313** [comment]
@thedeeno I'm getting the same error mentioned above -- any ideas for a work around or fix? I'm happy to put together a pull request if you can get me started in the right direction.

**Comment by thedeeno** [comment]
Sorry everyone. I wrote the first version of the plugin system for WCT and it has since undergone some evolution. This plugin was written for an alpha version of WCT and as such is just broken in version 1. I'm not currently on a polymer project so I don't currently have time to bring this plugin back up to speed.

@apowers313 If you want to give upgrading a go you might want to look into the following: One of the problems we had to solve initially was figuring out how to pass arbitrary data from the browser session back to the express server. Istanbul will instrument the code and a specific key with all the coverage results. We attached this key to a special WCT variable on window and then passed the WCT variable back at `sub-suite-end`. That's why you see `data.__coverage__` data is the global WCT session object and `__coverage__` is the key istanbul injected results into.

The above appears to be broken now. This can be caused by many things unfortunately:
- WCT doesn't pass the `data` object into the `sub-suite-end` event listener anymore
- WCT passes a different global variable back as the data, so istanbul is attaching `__coverage__` to the wrong place
- Istanbul didn't propertly instrument the code, therefore `__coverage__` will always be undefined

I hope the above helps. I'm happy to answer specific questions you have when exploring this, I just don't have enough context about the current state of WCT to direct you more specifically.

**Comment by apowers313** [comment]
@thedeeno thanks for the pointers, the good news is that the .js is being instrumented and `sub-suite-end` is being returned with the `data` object. The bad news is that the browser isn't creating `__coverage__` and putting it in the right spot.

Here's my instrumented browser-side code, and "DOING SOMETHING" (which is printed deep in the middle of that mess) ends up being printed 4 times in Chrome's console:
http://pastebin.com/MFHvz6U1

Sadly, I can't figure out where the `__coverage__` ends up amongst all the browser variables. `WCT.share` exists, but is empty. Changing `istanbul.Instrumenter()` to use the default of a global `__coverage__` variable doesn't make `__coverage__` appear in the global scope either.

I'm stuck -- any thoughts?
